spring:
  application:
    name: chat-ai-java-spring
  ai:
    openai:
#      Comment out the traditional OpenAI key
#      api-key: ${OPENAI_API_KEY}
      api-key: ${HUGGINGFACE_API_KEY}
      base-url: https://xxxx.us-east-1.aws.endpoints.huggingface.cloud
      chat:
        options:
#           Comment out the traditional OpenAI model
#           model: gpt-5-nano
            model: Qwen/Qwen2.5-Coder-7B-Instruct
    vertex:
      ai:
        gemini:
          project-id: ${GOOGLE_PROJECT_ID}
          location: ${GOOGLE_LOCATION}
          chat:
            options:
              model: ${GOOGLE_VERTEX_MODEL}
    huggingface:
      chat:
        api-key: ${HUGGINGFACE_API_KEY}
        url: https://xxxx.us-east-1.aws.endpoints.huggingface.cloud
        options:
          model: Qwen/Qwen2.5-Coder-7B-Instruct
          max-new-tokens: 1024
          temperature: 0.7
server:
  port: 9080
